[package]
name = "tricorder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
serde_json = "1.0.149"
